services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - wp-network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.7.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - wp-network

  act62-webserver:
    depends_on:
      - wordpress
    image: nginx:1.26.2-alpine
    container_name: act62-webserver
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - wp-network

volumes:
  wordpress:
  dbdata:

networks:
  wp-network:
    driver: bridge